// <auto-generated />
using System;
using Alphastellar_WebAPI_Project.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alphastellar_WebAPI_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220517134305_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alphastellar_WebAPI_Project.Models.Entities.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Boats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colour = "Blue",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1693),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Colour = "Black",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1695),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Colour = "White",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1696),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Colour = "Red",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1697),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Colour = "Black",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1698),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Alphastellar_WebAPI_Project.Models.Entities.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colour = "Black",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1603),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Colour = "White",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1605),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Colour = "Red",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1606),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Colour = "Blue",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1607),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Colour = "Red",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1608),
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Colour = "Blue",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1609),
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Colour = "White",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1610),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Colour = "Black",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1611),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Alphastellar_WebAPI_Project.Models.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Headlights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colour = "Red",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1377),
                            Headlights = "On",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Colour = "Blue",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1393),
                            Headlights = "Off",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 3,
                            Colour = "Black",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1395),
                            Headlights = "Off",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 4,
                            Colour = "White",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1396),
                            Headlights = "Off",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 5,
                            Colour = "Red",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1397),
                            Headlights = "Off",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 6,
                            Colour = "Blue",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1398),
                            Headlights = "On",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 7,
                            Colour = "Black",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1400),
                            Headlights = "On",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 8,
                            Colour = "White",
                            CreateDate = new DateTime(2022, 5, 17, 16, 43, 5, 592, DateTimeKind.Local).AddTicks(1401),
                            Headlights = "Off",
                            Status = 1,
                            Wheels = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
